Repository OkinawaOpenLaboratory/fiware-meteoroid, pull requests merged in 2020-01, with the labels that each got.

#7 Feature/support java, and propose the structure about languages documentation directory
  README.md
  docs/README.md
  docs/function/java.md
  docs/function/python.md
  meteoroid/core/libs/decorators.py
  meteoroid/core/libs/faas_driver.py
  meteoroid/core/serializers.py
Labels: documentation, enhancement

#12 Add trigger and rule to OpenWhisk Client
  .travis.yml
  meteoroid/core/libs/clients/open_whisk_client.py
  meteoroid/core/tests/__init__.py
  meteoroid/core/tests/libs/__init__.py
  meteoroid/core/tests/libs/clients/__init__.py
  meteoroid/core/tests/libs/clients/test_open_whisk_client.py
  meteoroid/core/tests/tests.py
Labels: all reviewers, enhancement

#13 Feature/lint
  .flake8
  .travis.yml
  meteoroid/core/api_views.py
  meteoroid/core/libs/clients/open_whisk_client.py
  meteoroid/core/libs/decorators.py
  meteoroid/core/libs/faas_driver.py
  meteoroid/core/models.py
  meteoroid/core/tests/tests.py
  meteoroid/core/views.py
  meteoroid/meteoroid/urls.py
Labels: all reviewers

#14 Feature/logging
  Dockerfile
  meteoroid/core/libs/clients/open_whisk_client.py
  meteoroid/core/libs/clients/orion_subscription_client.py
  meteoroid/core/libs/decorators.py
  meteoroid/core/libs/faas_driver.py
  meteoroid/meteoroid/check_environment.py
  meteoroid/meteoroid/settings.py
Labels: all reviewers

#16 Add flake8 plugins, and I updated existing packages.
  .flake8
  Pipfile
  Pipfile.lock
  README.md
  docs/manuals/contribution_guidelines.md
  meteoroid/core/admin.py
  meteoroid/core/api_urls.py
  meteoroid/core/api_views.py
  meteoroid/core/libs/clients/open_whisk_client.py
  meteoroid/core/libs/clients/orion_subscription_client.py
  meteoroid/core/libs/decorators.py
  meteoroid/core/libs/faas_driver.py
  meteoroid/core/serializers.py
  meteoroid/core/tests/libs/clients/test_open_whisk_client.py
  meteoroid/meteoroid/check_environment.py
  meteoroid/meteoroid/settings.py
  meteoroid/meteoroid/urls.py
Labels: all reviewers

#15 Add Schedule resource to Meteoroid
  README.md
  meteoroid/core/admin.py
  meteoroid/core/api_urls.py
  meteoroid/core/api_views.py
  meteoroid/core/libs/clients/open_whisk_client.py
  meteoroid/core/libs/decorators.py
  meteoroid/core/libs/faas_driver.py
  meteoroid/core/migrations/0007_schedule.py
  meteoroid/core/models.py
  meteoroid/core/serializers.py
  meteoroid/core/tests/libs/clients/test_open_whisk_client.py
  meteoroid/core/tests/test_api_views.py
  meteoroid/core/tests/test_models.py
  meteoroid/core/tests/test_serializers.py
Labels: all reviewers

#19 Fixed the result fields length
  meteoroid/core/api_views.py
  meteoroid/core/libs/faas_driver.py
  meteoroid/core/serializers.py
Labels: all reviewers

#20 Change image version to 0.2
  docker/docker-compose.yml
Labels: all reviewers
